/* Local multi-pass OCR. Perspective/grid detection is optional, never a prerequisite. */
(function(root){
let preparing=null;
const cancel=()=>{if(preparing)preparing.abort()};
// Optional local ink refinement, bounded to one text-derived trip row.
// Missing ink never stops OCR and cannot move to the next employee.
function refine(source,layout){const ctx=source.getContext('2d');for(const c of layout.cells){const slope=layout.rowLines[c.type].a,half=layout.rowLines.step*.65,left=Math.max(0,Math.round(c.x-c.width*.42)),width=Math.max(1,Math.round(c.width*.84)),top=Math.max(0,Math.floor(c.y-half)),height=Math.min(source.height-top,Math.ceil(half*2));if(height<4)continue;const pix=ctx.getImageData(left,top,width,height),counts=[];for(let y=0;y<height;y++){let n=0;for(let x=0;x<width;x++){const yy=Math.round(y+slope*(left+x-c.x));if(yy<0||yy>=height)continue;const i=(yy*width+x)*4;if(pix.data[i]+pix.data[i+1]+pix.data[i+2]<480)n++}counts.push(n>=2&&n<width*.72)}const runs=[];for(let y=0;y<height;){if(!counts[y]){y++;continue}const start=y;while(y<height&&counts[y])y++;if(y-start>=layout.rowLines.height*.45)runs.push({center:top+(start+y)/2,height:y-start})}runs.sort((a,b)=>Math.abs(a.center-c.y)-Math.abs(b.center-c.y));const r=runs[0];if(r&&Math.abs(r.center-c.y)<layout.rowLines.step*.28){c.y=r.center;c.height=Math.min(Math.round(r.height+5),Math.floor(layout.rowLines.step*.94));c.top=Math.floor(c.y-c.height/2)}}return layout;}
function padded(part){const pad=18,canvas=document.createElement('canvas');canvas.width=part.canvas.width+pad*2;canvas.height=part.canvas.height+pad*2;const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(part.canvas,pad,pad);return {canvas,map:p=>part.map({x:p.x-pad,y:p.y-pad})};}
function frame(source,left,top,width,height,slope=0,scale=1){if(Math.abs(slope)<.01)slope=0;const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw Error('CANVAS_UNAVAILABLE');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.setTransform(scale,-slope*scale,0,scale,-left*scale,(slope*left-top)*scale);ctx.drawImage(source,0,0);return {canvas,map:p=>({x:left+p.x/scale,y:top+p.y/scale+slope*p.x/scale})};}
async function pass(worker,run,source,info,psm,whitelist,progress){progress(info.title);await run(worker.setParameters({tessedit_pageseg_mode:String(psm),tessedit_char_whitelist:whitelist,preserve_interword_spaces:'1'}));const r=await run(worker.recognize(source.canvas,{}, {text:true,blocks:true,tsv:true}));if(!r||!r.data||typeof r.data.text!=='string')throw Error('OCR_RESULT_INVALID');return {...info,text:r.data.text,tokens:OcrStructure.tokens(r.data,source.map,info.id)};}
async function initial(source,worker,run,progress,onData,known){const passes=[];const first=await pass(worker,run,{canvas:source,map:p=>p},{id:'pass1',title:'画像を文字データへ変換しています… PASS 1 全体（日本語＋英語）'},11,'',progress);passes.push(first);onData(passes);const height=known?Math.min(source.height,Math.max(source.height*.25,known.dateY+source.width*.3)):source.height*.32;const head=frame(source,0,0,source.width,height,0,Math.min(1.5,2000/source.width));try{passes.push(await pass(worker,run,head,{id:'pass2',title:'画像を文字データへ変換しています… PASS 2 日付欄'},11,'0123456789',progress))}finally{head.canvas.width=1}onData(passes);return passes;}
async function prepare(source,name,progress=()=>{},onData=()=>{}){cancel();const controller=new AbortController();preparing=controller;try{const passes=await PhotoReader.withWorker('jpn+eng',controller.signal,async(w,run)=>{const passes=await initial(source,w,run,progress,onData);if(!OcrStructure.nameAnchor(passes.flatMap(p=>p.tokens),name)){const names=frame(source,0,0,source.width*.4,source.height,0,Math.min(2,2200/source.height));try{passes.push(await pass(w,run,names,{id:'names',title:'氏名欄を拡大して照合しています…'},11,'',progress));onData(passes)}finally{names.canvas.width=1}}return passes});const ts=passes.flatMap(p=>p.tokens),namePick=OcrStructure.nameAnchor(ts,name),datePick=namePick?OcrStructure.autoDates(ts,source.width,source.height,namePick.nameX):{};return {passes,pick:{...namePick,...datePick}}}finally{if(preparing===controller)preparing=null}}
async function read(source,pick,name,cached,progress,onData,signal){let passes=cached?.passes?cached.passes.slice():[],errors=[],layout;
 try{await PhotoReader.withWorker('jpn+eng',signal,async(w,run)=>{
  if(!passes.some(p=>p.id==='pass1')||!passes.some(p=>p.id==='pass2'))passes=await initial(source,w,run,progress,partial=>{passes=partial.slice();onData(passes)},pick);
  await run(w.reinitialize('eng'));
  let ts=passes.flatMap(p=>p.tokens);progress('勤務表を解析しています… 文字の座標から日付列と本人行を推定');layout=OcrStructure.structure(ts,pick,source.width,source.height);
  const row=layout.rowLines,slope=(row.second.a+row.third.a)/2,left=Math.max(0,pick.nameX),radius=row.reliable?row.step*1.7:Math.max(row.step*2.5,source.width*.13),top=pick.nameY+slope*(left-pick.nameX)-radius;
  const person=frame(source,left,top,source.width-left,radius*2,slope,Math.min(2,2000/(source.width-left)));
  try{passes.push(await pass(w,run,person,{id:'pass3',title:'画像を文字データへ変換しています… PASS 3 本人付近（数字優先）'},11,'0123456789',progress))}finally{person.canvas.width=1}
  onData(passes);ts=passes.flatMap(p=>p.tokens);layout=refine(source,OcrStructure.structure(ts,pick,source.width,source.height));
  // Narrow retries use the text-derived intersections, not detected grid cells.
  const uncertain=OcrStructure.candidates(ts,layout).filter(c=>c.state==='unresolved');
  for(let i=0;i<uncertain.length;i++){if(signal?.aborted)throw Error('READ_CANCELLED');const c=uncertain[i];if(c.width<8||c.height<6)continue;const slope=layout.rowLines[c.type].a,part=frame(source,c.left,c.y-c.height/2+slope*(c.left-c.x),c.width,c.height,slope,4),input=padded(part);try{passes.push(await pass(w,run,input,{id:`retry-${c.day}-${c.type}`,title:`シフト候補を作成しています… ${c.day}日 ${c.type==='second'?'2便':'3便'}の文字を再確認 (${i+1}/${uncertain.length})`},7,'0123456789',progress));const first=passes[passes.length-1];if(first.text.trim()&&!first.tokens.some(t=>/^\d{3}$/.test(t.text.trim())&&t.confidence>=90)){passes.push(await pass(w,run,input,{id:`alternate-${c.day}-${c.type}`,title:`シフト候補を作成しています… ${c.day}日の不鮮明な文字を照合`},8,'0123456789',progress))}}finally{part.canvas.width=1;input.canvas.width=1}}
  onData(passes);
 })}catch(error){if(error.message==='READ_CANCELLED')throw error;errors.push(error.message);progress('OCRの一部を確定できませんでした。認識済みの文字と未確定欄で確認画面へ進みます。');onData(passes)}
 if(signal?.aborted)throw Error('READ_CANCELLED');const ts=passes.flatMap(p=>p.tokens);layout=layout||OcrStructure.structure(ts,pick,source.width,source.height);
 const checked=OcrStructure.rowLines(ts,pick,source.width),supported=checked.reliable&&layout.cells.every(c=>Math.abs(checked[c.type].a*c.x+checked[c.type].b-c.y)<checked.step*.4);
 if(supported){layout.rowLines=checked;for(const c of layout.cells)c.uncertain=c.column.support<3;layout.diagnostics.push('本人行：セル再読取の文字座標で照合済み')}
 const cells=OcrStructure.candidates(ts,layout),rows={},evidence=[];
 if(!supported&&!layout.rowLines.reliable&&!layout.rowLines.manual){layout.diagnostics.push('本人行の根拠不足：誤った社員の数字を採用せず未確定。写真の位置指定で2便行を追加指定できます。');for(const c of cells){c.value='';c.state='unresolved';c.uncertain=true}}
 for(const c of cells){const slope=layout.rowLines[c.type].a;let url='',blank=false;if(c.width>=8&&c.height>=6){const part=frame(source,c.left,c.y-c.height/2+slope*(c.left-c.x),c.width,c.height,slope,2);const pixels=part.canvas.getContext('2d').getImageData(0,0,part.canvas.width,part.canvas.height);blank=!c.value&&!c.uncertain&&!errors.length&&ShiftGrid.isBlankCell(pixels,{left:0,top:0,width:pixels.width,height:pixels.height});url=part.canvas.toDataURL('image/png');part.canvas.width=1}const state=errors.length?'unresolved':blank?'blank':c.state;rows[c.day]??={states:{}};rows[c.day][c.type]=c.value;rows[c.day].states[c.type]=state;evidence.push({...c,url,blank,state})}
 for(const row of Object.values(rows))row.off=!row.second&&!row.third;
 return {rows,evidence,passes,layout,errors};
}
// Geometry is an auxiliary pass: failure always retains the original OCR path.
async function auxiliary(source,signal,progress){return new Promise((resolve,reject)=>{let worker,timer,done=false;const finish=value=>{if(done)return;done=true;clearTimeout(timer);worker?.terminate();signal?.removeEventListener('abort',abort);resolve(value)},abort=()=>{finish(null)};if(signal?.aborted)return finish(null);try{worker=new Worker(new URL('./image-worker.js?v=18',location.href));timer=setTimeout(()=>finish(null),20000);signal?.addEventListener('abort',abort,{once:true});worker.onerror=()=>finish(null);worker.onmessage=e=>{if(e.data.progress){progress('位置を整えています… '+e.data.progress);return}finish(e.data.result||null)};const image=source.getContext('2d').getImageData(0,0,source.width,source.height);worker.postMessage({image},[image.data.buffer])}catch(_){finish(null)}})}
async function alignedRead(source,pick,name,cached,progress,onData,signal){
 const corrected=await auxiliary(source,signal,progress);if(signal?.aborted)throw Error('READ_CANCELLED');
 if(!corrected)return read(source,pick,name,cached,progress,onData,signal);
 const canvas=document.createElement('canvas');canvas.width=corrected.image.width;canvas.height=corrected.image.height;canvas.getContext('2d').putImageData(new ImageData(corrected.image.data,canvas.width,canvas.height),0,0);
 const mapped={...pick};for(const key of ['name','date','second','third'])if(Number.isFinite(pick[key+'X'])&&Number.isFinite(pick[key+'Y'])){const p=PhotoGeometry.point(corrected.matrix,{x:pick[key+'X'],y:pick[key+'Y']});mapped[key+'X']=p.x;mapped[key+'Y']=p.y}
 // Row spacing is expressed in image pixels and must be re-estimated after warping.
 delete mapped.rowStep;
 try{let result;
 try{const pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height),grid=ShiftGrid.refineRows(pixels,await PhotoReader.locateGrid(pixels,mapped,signal));if(!grid.cells?.length||grid.cells.some(c=>c.uncertain||c.unavailable))throw Error('補助座標の根拠不足');const scanned=await PhotoReader.readCells(pixels,grid,(c,i,n)=>progress(`セルを読み取っています… ${c.day}日 ${c.type==='second'?'2便':'3便'} (${i+1}/${n})`),signal);result={...scanned,passes:[],errors:[],layout:{...grid,dayColumns:grid.edges.slice(1).map((x,i)=>({day:mapped.firstDate+i,x:(x+grid.edges[i])/2})),diagnostics:['文字の出現順を使わず、本人行と日付列の交点をセルごとに読取',...(grid.diagnostics||[])]}};result.passes=[{id:'cells',title:'補正後セル別OCR',text:scanned.evidence.map(c=>c.day+'日 '+c.type+': '+c.raw+' ('+c.confidence+')').join('\n'),tokens:scanned.evidence}];onData(result.passes)}catch(error){if(signal?.aborted)throw Error('READ_CANCELLED');progress('補助座標を確定できませんでした。文字の位置から読み取りを続けます…');result=await read(canvas,mapped,name,null,progress,onData,signal)}
 result.layout.diagnostics.unshift('自動位置補正：成功。氏名・日付タップを補正後の座標へ変換');result.layout.corrected=true;result.layout.sourceMatrix=corrected.matrix;
 // The picker still displays the original photo; map overlay cell centres back.
 for(const c of result.layout.cells){c.overlay=[{x:c.left,y:c.top},{x:c.left+c.width,y:c.top},{x:c.left+c.width,y:c.top+c.height},{x:c.left,y:c.top+c.height}].map(p=>PhotoGeometry.point(corrected.inverse,p));const p=PhotoGeometry.point(corrected.inverse,{x:c.x??c.left+c.width/2,y:c.y??c.top+c.height/2});c.x=p.x;c.y=p.y}return result}finally{canvas.width=1}
}
root.OcrFirst={prepare,read:alignedRead,cancel};
})(window);
